---
on:
  - pull_request
name: "Tartufo Scan"
jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: godaddy/tartufo-action@d95293febe8f40a6b8ee3ac0acebfc36c3b7e0d1 # 4.1.0
        id: tartufo
        with:
          entropy: "true"
          regex: "true"
          scan-filenames: "true"
          include-submodule: "false"
