---
on:
  - pull_request
name: "Tartufo Scan"
jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: godaddy/tartufo-action@d95293febe8f40a6b8ee3ac0acebfc36c3b7e0d1 # 4.1.0
        id: tartufo
        with:
          entropy: "true"
          regex: "true"
          scan-filenames: "true"
          include-submodule: "false"
